# Generated by Django 3.2.6 on 2021-08-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
